# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download
    - go mod verify

builds:
  - id: oauth2-proxy
    binary: oauth2-proxy
    ldflags:
      - -s -w
      - -X github.com/oauth2-proxy/oauth2-proxy/v7/pkg/version.VERSION={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: oauth2-proxy
    builds:
      - oauth2-proxy
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - CHANGELOG.md

nfpms:
  - id: oauth2-proxy
    package_name: oauth2-proxy
    builds:
      - oauth2-proxy
    vendor: jakubp5
    homepage: https://github.com/jakubp5/oauth
    maintainer: "jakubp5 <jakub@example.com>"
    description: "OAuth2 Proxy - A reverse proxy that provides authentication with Google, Github or other providers"
    license: MIT
    bindir: /usr/bin

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

release:
  github:
    owner: jakubp5
    name: oauth
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## OAuth2 Proxy ({{ .Version }})

    For more information, please see the [documentation](https://github.com/jakubp5/oauth/blob/main/README.md). 