name: goreleaser

on:
  push:
    tags:
      - '*'
  pull_request_target:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    if: github.event_name == 'push' || (github.event_name == 'pull_request_target' && github.event.pull_request.merged)
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "disabled"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
